"""
For coding this part of the backend we used Antigravity with Gemini 3.1 Pro
"""
from django.db import models
from django.contrib.auth.models import User

class MedicalRecord(models.Model):
    # Link record to a user (mandatory since predictions require an account)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    
    age = models.IntegerField()
    gender = models.CharField(max_length=10) # Using CharField to be flexible (e.g., "Male", "Female", or '0'/'1')
    heart_rate = models.IntegerField()
    #Generated by Antigravity with Gemini 3.1: verbose_name is just an optional human-readable label for a database column
    systolic_bp = models.IntegerField(verbose_name="Systolic blood pressure")
    diastolic_bp = models.IntegerField(verbose_name="Diastolic blood pressure")
    blood_sugar = models.FloatField()
    ck_mb = models.FloatField(verbose_name="CK-MB", blank=True, null=True)
    troponin = models.FloatField(blank=True, null=True)

    # Store the prediction result (risk percentage)
    result = models.FloatField(blank=True, null=True, help_text="Risk percentage (0-100)")
    
    # Store SHAP values for explainability
    shap_values = models.JSONField(blank=True, null=True)
    
    created_at = models.DateTimeField(auto_now_add=True)


class Patient(models.Model):
    # Generated by Antigravity with Gemini 3.1
    doctor = models.ForeignKey(User, on_delete=models.CASCADE, related_name="doctor_patients")
    # Link to the actual User account of the patient
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="patient_profile")
    
    age = models.IntegerField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

