# the idea of including it is suggested by Antigravity with Gemini 3.1 Pro
# serializers act like a dedicated "translation department" 
# between your Django database and  frontend HTML code 
from rest_framework import serializers
from .models import MedicalRecord, Patient

# Serializer for the MedicalRecord model.
# This handles converting MedicalRecord database objects to JSON for the API, 
# and validating incoming JSON data to create new MedicalRecord entries.
class MedicalRecordSerializer(serializers.ModelSerializer):
    class Meta:
        model = MedicalRecord
        # The fields that are allowed to be read from or written to via the API.
        fields = [
            'id', 'age', 'gender', 'heart_rate', 
            'systolic_bp', 'diastolic_bp', 
            'blood_sugar', 'ck_mb', 'troponin',
            'result', 'created_at', 'shap_values'
        ]
        # These fields are generated by the backend
        # users cannot modify these directly through the API.
        read_only_fields = ['id', 'result', 'created_at', 'shap_values']

# Serializer for the Patient link model.
# This represents the relationship between a Doctor and a Patient.
class PatientSerializer(serializers.ModelSerializer):
    # These fields pull data directly from the linked User account, 
    # making it easy to display the patient's real name and email on the doctor dashboard.
    first_name = serializers.CharField(source='user.first_name', read_only=True)
    last_name = serializers.CharField(source='user.last_name', read_only=True)
    email = serializers.EmailField(source='user.email', read_only=True)

    class Meta:
        model = Patient
        # 'user' - the mandatory database-generated number for the actual human being's generic account in the main User table.
        fields = ['id', 'doctor', 'user', 'first_name', 'last_name', 'email', 'age', 'created_at']
        # The doctor reading the API data shouldn't be able to change the core relationship links or timestamp due to security reasons.
        read_only_fields = ['doctor', 'created_at', 'user']
