"""
URL configuration for heartproject.
"""
from django.urls import path
from . import views

from rest_framework_simplejwt.views import (
    #next 2 lines generated by AI to implement tokens 
    TokenObtainPairView,
    TokenRefreshView,
)

urlpatterns = [
    path('', views.home, name='home'),
    path('auth/', views.auth, name='auth'),
    #next 2 lines generated by AI to implement tokens 
    # The 'Login' - returns Access and Refresh tokens
    path('api/login/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    # The 'Renewer' - send refresh token here to get new access token
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    
]
