# Generated by Django 6.0 on 2026-01-03 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('heart_rate', models.IntegerField()),
                ('systolic_bp', models.IntegerField(verbose_name='Systolic blood pressure')),
                ('diastolic_bp', models.IntegerField(verbose_name='Diastolic blood pressure')),
                ('blood_sugar', models.FloatField()),
                ('ck_mb', models.FloatField(verbose_name='CK-MB')),
                ('troponin', models.FloatField()),
                ('result', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
