# Generated by Django 5.2.7 on 2026-01-06 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0003_alter_medicalrecord_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='shap_values',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
