# Generated by Django 5.2.7 on 2026-02-04 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0007_remove_patient_email_remove_patient_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='ck_mb',
            field=models.FloatField(blank=True, null=True, verbose_name='CK-MB'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='troponin',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
