# Generated by Django 5.2.7 on 2026-03-06 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0008_alter_medicalrecord_ck_mb_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='patient_id',
        ),
    ]
